language: java


jdk: openjdk8

script:
  - echo "Hola Travis"
  - mvn package
  - chmod 400 instancia.pem
  - ssh-keyscan -H 18.222.191.223 >> ~/.ssh/known_hosts
  - ssh-keyscan -H ec2-18-222-191-223.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  #- scp -i "instancia.pem" ubuntu@18.222.191.223 "rm -rf /var/lib/tomcat8/webapps/Netflix*
  - echo "si se pudo"
  - scp -i "instancia.pem" target/Netflix-1.0-SNAPSHOT.war ubuntu@18.222.191.223:/var/lib/tomcat8/webapps/Netflix.war